enum USER {ABSENT,PRESENT,LOADING}
enum LOGIN {LOGGING_IN , IDLE}
enum REGISTER {CREATING , IDLE}
enum ACCOUNT_TYPE {PRIVATE,PUBLIC}
enum CREATE_POST {CREATING,IDLE}
enum FOLLOWING_USER {FOLLOWING,IDLE}
enum POSTS_STATE {PRESENT,ABSENT,LOADING}
enum POST_TYPE {VIDEO,IMAGE,TEXT}
enum FETCH_SELF_POST {FETCHING,FETCHED,NOT_FETCHED}
enum MESSAGE_TYPE {TEXT,IMAGE}
enum STORY_TYPE{TEXT,POST,VIDEO,IMAGE}
enum FETCH_FEED_STORY{FETCHING,FETCHED,NOT_FETCHED}
enum FETCH_SAVED_POSTS{FETCHING,FETCHED,NOT_FETCHED}