enum USER {ABSENT,PRESENT,LOADING}
enum LOGIN {LOGGING_IN , IDLE}
enum REGISTER {CREATING , IDLE}
enum ACCOUNT_TYPE {PRIVATE,PUBLIC}
enum CREATE_POST {CREATING,IDLE}
enum FOLLOWING_USER {FOLLOWING,IDLE}